Fast js updates
fast-af/devportal pull request #33
Opened 2021-07-28 12:57 UTC by fasterSean

# Updates
* Add new information for FastJS @brikr 
* Remove dev rel stuff https://fastaf.slack.com/archives/C014VRDRUC8/p1627416269247700
* Remove discord https://fastaf.slack.com/archives/C01J1G8NAAW/p1627415900290500

2021-07-28 15:48 UTC, zjoekr approved these changes

2021-07-28 17:06 UTC, brikr requested changes
Thanks for doing this! Two other things apart from the comments I left in-line:
1. The structure of the fast.js docs is a little bit off. I think you can ditch the `Open Fast Checkout when the button is clicked` sub-header, and the `Handle events from Fast Checkout` header should be top-level as it works with both methods of initiating checkout.
2. We decided a bit after these docs were written that we would refer to the library as "fast.js" in all cases code or otherwise. Can you do a pass through the docs and remove any "Fast.js" or `fast.js` (inline code block), and replace with just "fast.js"?

2021-07-28 17:06 UTC, brikr commented on index.mdx
> +      to="https://updates.fastdevs.co/"
is fastdevs.co still sticking around?

2021-07-28 17:06 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +| **disabled**        | Optional | disbaled will prevent the button from fucntioning and show a disbaled state.
```suggestion
| **disabled**        | Optional | disabled will prevent the button from functioning and show a disabled state.                                                                                                                                                     |
```

2021-07-28 17:06 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +| **currency**        | Optional | currency is the string value of currency for the purchased.
```suggestion
| **currency**        | Optional | currency is the string value of currency for the purchase.                                                                                                                                                                      |
```

2021-07-28 17:06 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +Properties can be added to allow for integration without Javascript.
```suggestion
Properties can be added to allow for integration without JavaScript.
```

2021-07-28 17:16 UTC, fasterSean commented on index.mdx
> +      to="https://updates.fastdevs.co/"
I'm not sure let me check

2021-07-28 19:57 UTC, brikr requested changes
mostly grammar

2021-07-28 19:57 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +- `Checkout Cart - Button Clicked` is emited when "Fast Checkout" button clicked on cart page.
```suggestion
- `Buy Now - Button Clicked` is emitted when the "Fast Checkout" button is clicked on the product page.
- `Checkout Cart - Button Clicked` is emitted when the "Fast Checkout" button is clicked on the cart page.
```

2021-07-28 19:57 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +- `Checkout - Order Cancelled` is emited when the order has been cancelled from inside the Fast checkout window.
```suggestion
- `Checkout - Order Created` is emitted when the order has been submitted through Fast Checkout.
- `Checkout - Order Updated` is emitted when the order has changed while inside the Fast Checkout window.
- `Checkout - Order Cancelled` is emitted when the order has been canceled from inside the Fast Checkout window.
```

2021-07-28 19:57 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +These event emit:
```suggestion
These events emit:
```

2021-07-28 19:57 UTC, brikr commented on developer-portal/fast-api-fastjs.md
> +These events are useful if you wish to forward data to your analytics provider, or if you want to do things like redirect to an order complete page after the user has finished their order and closed
can you update the sample event watcher below to use an event that is real? 😅

2021-07-28 19:57 UTC, brikr commented on developer-portal/fast-api-reference-fast-js.md
>  These are all of the events that are currently supported, when they are sent, and what extra properties they contain.
should this link to that event list on the other page?

2021-07-29 20:51 UTC, brikr approved these changes

2021-07-29 20:57 UTC, merged